// Code generated by ent, DO NOT EDIT.

package hostconfig

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the hostconfig type in the database.
	Label = "host_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldConfig holds the string denoting the config field in the database.
	FieldConfig = "config"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// EdgeDevice holds the string denoting the device edge name in mutations.
	EdgeDevice = "device"
	// Table holds the table name of the hostconfig in the database.
	Table = "host_configs"
	// DeviceTable is the table that holds the device relation/edge.
	DeviceTable = "host_configs"
	// DeviceInverseTable is the table name for the Device entity.
	// It exists in this package in order to avoid circular dependency with the "device" package.
	DeviceInverseTable = "devices"
	// DeviceColumn is the table column denoting the device relation/edge.
	DeviceColumn = "device_configs"
)

// Columns holds all SQL columns for hostconfig fields.
var Columns = []string{
	FieldID,
	FieldConfig,
	FieldType,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "host_configs"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"device_configs",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// ConfigValidator is a validator for the "config" field. It is called by the builders before save.
	ConfigValidator func([]byte) error
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
)

// OrderOption defines the ordering options for the HostConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByDeviceField orders the results by device field.
func ByDeviceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDeviceStep(), sql.OrderByField(field, opts...))
	}
}
func newDeviceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DeviceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DeviceTable, DeviceColumn),
	)
}
