// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DevicesColumns holds the columns for the "devices" table.
	DevicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "public_key", Type: field.TypeString, Unique: true},
		{Name: "certificate", Type: field.TypeString, Unique: true},
	}
	// DevicesTable holds the schema information for the "devices" table.
	DevicesTable = &schema.Table{
		Name:       "devices",
		Columns:    DevicesColumns,
		PrimaryKey: []*schema.Column{DevicesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "device_public_key",
				Unique:  false,
				Columns: []*schema.Column{DevicesColumns[1]},
			},
		},
	}
	// HostConfigsColumns holds the columns for the "host_configs" table.
	HostConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "config", Type: field.TypeBytes},
		{Name: "type", Type: field.TypeString},
		{Name: "device_configs", Type: field.TypeInt},
	}
	// HostConfigsTable holds the schema information for the "host_configs" table.
	HostConfigsTable = &schema.Table{
		Name:       "host_configs",
		Columns:    HostConfigsColumns,
		PrimaryKey: []*schema.Column{HostConfigsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "host_configs_devices_configs",
				Columns:    []*schema.Column{HostConfigsColumns[3]},
				RefColumns: []*schema.Column{DevicesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "hostconfig_type_device_configs",
				Unique:  true,
				Columns: []*schema.Column{HostConfigsColumns[2], HostConfigsColumns[3]},
			},
		},
	}
	// RevocationsColumns holds the columns for the "revocations" table.
	RevocationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "revocation", Type: field.TypeBytes},
		{Name: "hash", Type: field.TypeString, Unique: true},
		{Name: "hasher", Type: field.TypeUint64},
	}
	// RevocationsTable holds the schema information for the "revocations" table.
	RevocationsTable = &schema.Table{
		Name:       "revocations",
		Columns:    RevocationsColumns,
		PrimaryKey: []*schema.Column{RevocationsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_client_hashing_options", Type: field.TypeJSON},
		{Name: "password_server_hashing_options", Type: field.TypeJSON},
		{Name: "password_double_hashed", Type: field.TypeBytes},
		{Name: "certificate", Type: field.TypeString, Unique: true},
		{Name: "public_key", Type: field.TypeString, Unique: true},
		{Name: "encrypted_private_key", Type: field.TypeBytes},
		{Name: "totp_secret", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_username",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[1]},
			},
			{
				Name:    "user_public_key",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DevicesTable,
		HostConfigsTable,
		RevocationsTable,
		UsersTable,
	}
)

func init() {
	HostConfigsTable.ForeignKeys[0].RefTable = DevicesTable
}
