// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"github.com/rahn-it/svalin/ent/hostconfig"
	"github.com/rahn-it/svalin/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HostConfigDelete is the builder for deleting a HostConfig entity.
type HostConfigDelete struct {
	config
	hooks    []Hook
	mutation *HostConfigMutation
}

// Where appends a list predicates to the HostConfigDelete builder.
func (hcd *HostConfigDelete) Where(ps ...predicate.HostConfig) *HostConfigDelete {
	hcd.mutation.Where(ps...)
	return hcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (hcd *HostConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, hcd.sqlExec, hcd.mutation, hcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (hcd *HostConfigDelete) ExecX(ctx context.Context) int {
	n, err := hcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (hcd *HostConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(hostconfig.Table, sqlgraph.NewFieldSpec(hostconfig.FieldID, field.TypeInt))
	if ps := hcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, hcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	hcd.mutation.done = true
	return affected, err
}

// HostConfigDeleteOne is the builder for deleting a single HostConfig entity.
type HostConfigDeleteOne struct {
	hcd *HostConfigDelete
}

// Where appends a list predicates to the HostConfigDelete builder.
func (hcdo *HostConfigDeleteOne) Where(ps ...predicate.HostConfig) *HostConfigDeleteOne {
	hcdo.hcd.mutation.Where(ps...)
	return hcdo
}

// Exec executes the deletion query.
func (hcdo *HostConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := hcdo.hcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{hostconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (hcdo *HostConfigDeleteOne) ExecX(ctx context.Context) {
	if err := hcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
