// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"rahnit-rmm/ent/device"
	"rahnit-rmm/ent/tunnelconfig"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// TunnelConfig is the model entity for the TunnelConfig schema.
type TunnelConfig struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TunnelConfigQuery when eager-loading is set.
	Edges        TunnelConfigEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TunnelConfigEdges holds the relations/edges for other nodes in the graph.
type TunnelConfigEdges struct {
	// Device holds the value of the device edge.
	Device *Device `json:"device,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DeviceOrErr returns the Device value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TunnelConfigEdges) DeviceOrErr() (*Device, error) {
	if e.loadedTypes[0] {
		if e.Device == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: device.Label}
		}
		return e.Device, nil
	}
	return nil, &NotLoadedError{edge: "device"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TunnelConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tunnelconfig.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TunnelConfig fields.
func (tc *TunnelConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tunnelconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			tc.ID = int(value.Int64)
		default:
			tc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TunnelConfig.
// This includes values selected through modifiers, order, etc.
func (tc *TunnelConfig) Value(name string) (ent.Value, error) {
	return tc.selectValues.Get(name)
}

// QueryDevice queries the "device" edge of the TunnelConfig entity.
func (tc *TunnelConfig) QueryDevice() *DeviceQuery {
	return NewTunnelConfigClient(tc.config).QueryDevice(tc)
}

// Update returns a builder for updating this TunnelConfig.
// Note that you need to call TunnelConfig.Unwrap() before calling this method if this TunnelConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (tc *TunnelConfig) Update() *TunnelConfigUpdateOne {
	return NewTunnelConfigClient(tc.config).UpdateOne(tc)
}

// Unwrap unwraps the TunnelConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tc *TunnelConfig) Unwrap() *TunnelConfig {
	_tx, ok := tc.config.driver.(*txDriver)
	if !ok {
		panic("ent: TunnelConfig is not a transactional entity")
	}
	tc.config.driver = _tx.drv
	return tc
}

// String implements the fmt.Stringer.
func (tc *TunnelConfig) String() string {
	var builder strings.Builder
	builder.WriteString("TunnelConfig(")
	builder.WriteString(fmt.Sprintf("id=%v", tc.ID))
	builder.WriteByte(')')
	return builder.String()
}

// TunnelConfigs is a parsable slice of TunnelConfig.
type TunnelConfigs []*TunnelConfig
