// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"rahnit-rmm/ent/device"
	"rahnit-rmm/ent/predicate"
	"rahnit-rmm/ent/tunnelconfig"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TunnelConfigQuery is the builder for querying TunnelConfig entities.
type TunnelConfigQuery struct {
	config
	ctx        *QueryContext
	order      []tunnelconfig.OrderOption
	inters     []Interceptor
	predicates []predicate.TunnelConfig
	withDevice *DeviceQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TunnelConfigQuery builder.
func (tcq *TunnelConfigQuery) Where(ps ...predicate.TunnelConfig) *TunnelConfigQuery {
	tcq.predicates = append(tcq.predicates, ps...)
	return tcq
}

// Limit the number of records to be returned by this query.
func (tcq *TunnelConfigQuery) Limit(limit int) *TunnelConfigQuery {
	tcq.ctx.Limit = &limit
	return tcq
}

// Offset to start from.
func (tcq *TunnelConfigQuery) Offset(offset int) *TunnelConfigQuery {
	tcq.ctx.Offset = &offset
	return tcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tcq *TunnelConfigQuery) Unique(unique bool) *TunnelConfigQuery {
	tcq.ctx.Unique = &unique
	return tcq
}

// Order specifies how the records should be ordered.
func (tcq *TunnelConfigQuery) Order(o ...tunnelconfig.OrderOption) *TunnelConfigQuery {
	tcq.order = append(tcq.order, o...)
	return tcq
}

// QueryDevice chains the current query on the "device" edge.
func (tcq *TunnelConfigQuery) QueryDevice() *DeviceQuery {
	query := (&DeviceClient{config: tcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tunnelconfig.Table, tunnelconfig.FieldID, selector),
			sqlgraph.To(device.Table, device.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, tunnelconfig.DeviceTable, tunnelconfig.DeviceColumn),
		)
		fromU = sqlgraph.SetNeighbors(tcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TunnelConfig entity from the query.
// Returns a *NotFoundError when no TunnelConfig was found.
func (tcq *TunnelConfigQuery) First(ctx context.Context) (*TunnelConfig, error) {
	nodes, err := tcq.Limit(1).All(setContextOp(ctx, tcq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tunnelconfig.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tcq *TunnelConfigQuery) FirstX(ctx context.Context) *TunnelConfig {
	node, err := tcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TunnelConfig ID from the query.
// Returns a *NotFoundError when no TunnelConfig ID was found.
func (tcq *TunnelConfigQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tcq.Limit(1).IDs(setContextOp(ctx, tcq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tunnelconfig.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tcq *TunnelConfigQuery) FirstIDX(ctx context.Context) int {
	id, err := tcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TunnelConfig entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TunnelConfig entity is found.
// Returns a *NotFoundError when no TunnelConfig entities are found.
func (tcq *TunnelConfigQuery) Only(ctx context.Context) (*TunnelConfig, error) {
	nodes, err := tcq.Limit(2).All(setContextOp(ctx, tcq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tunnelconfig.Label}
	default:
		return nil, &NotSingularError{tunnelconfig.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tcq *TunnelConfigQuery) OnlyX(ctx context.Context) *TunnelConfig {
	node, err := tcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TunnelConfig ID in the query.
// Returns a *NotSingularError when more than one TunnelConfig ID is found.
// Returns a *NotFoundError when no entities are found.
func (tcq *TunnelConfigQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tcq.Limit(2).IDs(setContextOp(ctx, tcq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tunnelconfig.Label}
	default:
		err = &NotSingularError{tunnelconfig.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tcq *TunnelConfigQuery) OnlyIDX(ctx context.Context) int {
	id, err := tcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TunnelConfigs.
func (tcq *TunnelConfigQuery) All(ctx context.Context) ([]*TunnelConfig, error) {
	ctx = setContextOp(ctx, tcq.ctx, "All")
	if err := tcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TunnelConfig, *TunnelConfigQuery]()
	return withInterceptors[[]*TunnelConfig](ctx, tcq, qr, tcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tcq *TunnelConfigQuery) AllX(ctx context.Context) []*TunnelConfig {
	nodes, err := tcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TunnelConfig IDs.
func (tcq *TunnelConfigQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tcq.ctx.Unique == nil && tcq.path != nil {
		tcq.Unique(true)
	}
	ctx = setContextOp(ctx, tcq.ctx, "IDs")
	if err = tcq.Select(tunnelconfig.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tcq *TunnelConfigQuery) IDsX(ctx context.Context) []int {
	ids, err := tcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tcq *TunnelConfigQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tcq.ctx, "Count")
	if err := tcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tcq, querierCount[*TunnelConfigQuery](), tcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tcq *TunnelConfigQuery) CountX(ctx context.Context) int {
	count, err := tcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tcq *TunnelConfigQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tcq.ctx, "Exist")
	switch _, err := tcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tcq *TunnelConfigQuery) ExistX(ctx context.Context) bool {
	exist, err := tcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TunnelConfigQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tcq *TunnelConfigQuery) Clone() *TunnelConfigQuery {
	if tcq == nil {
		return nil
	}
	return &TunnelConfigQuery{
		config:     tcq.config,
		ctx:        tcq.ctx.Clone(),
		order:      append([]tunnelconfig.OrderOption{}, tcq.order...),
		inters:     append([]Interceptor{}, tcq.inters...),
		predicates: append([]predicate.TunnelConfig{}, tcq.predicates...),
		withDevice: tcq.withDevice.Clone(),
		// clone intermediate query.
		sql:  tcq.sql.Clone(),
		path: tcq.path,
	}
}

// WithDevice tells the query-builder to eager-load the nodes that are connected to
// the "device" edge. The optional arguments are used to configure the query builder of the edge.
func (tcq *TunnelConfigQuery) WithDevice(opts ...func(*DeviceQuery)) *TunnelConfigQuery {
	query := (&DeviceClient{config: tcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tcq.withDevice = query
	return tcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Config []byte `json:"config,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TunnelConfig.Query().
//		GroupBy(tunnelconfig.FieldConfig).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tcq *TunnelConfigQuery) GroupBy(field string, fields ...string) *TunnelConfigGroupBy {
	tcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TunnelConfigGroupBy{build: tcq}
	grbuild.flds = &tcq.ctx.Fields
	grbuild.label = tunnelconfig.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Config []byte `json:"config,omitempty"`
//	}
//
//	client.TunnelConfig.Query().
//		Select(tunnelconfig.FieldConfig).
//		Scan(ctx, &v)
func (tcq *TunnelConfigQuery) Select(fields ...string) *TunnelConfigSelect {
	tcq.ctx.Fields = append(tcq.ctx.Fields, fields...)
	sbuild := &TunnelConfigSelect{TunnelConfigQuery: tcq}
	sbuild.label = tunnelconfig.Label
	sbuild.flds, sbuild.scan = &tcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TunnelConfigSelect configured with the given aggregations.
func (tcq *TunnelConfigQuery) Aggregate(fns ...AggregateFunc) *TunnelConfigSelect {
	return tcq.Select().Aggregate(fns...)
}

func (tcq *TunnelConfigQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tcq); err != nil {
				return err
			}
		}
	}
	for _, f := range tcq.ctx.Fields {
		if !tunnelconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tcq.path != nil {
		prev, err := tcq.path(ctx)
		if err != nil {
			return err
		}
		tcq.sql = prev
	}
	return nil
}

func (tcq *TunnelConfigQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TunnelConfig, error) {
	var (
		nodes       = []*TunnelConfig{}
		_spec       = tcq.querySpec()
		loadedTypes = [1]bool{
			tcq.withDevice != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TunnelConfig).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TunnelConfig{config: tcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tcq.withDevice; query != nil {
		if err := tcq.loadDevice(ctx, query, nodes, nil,
			func(n *TunnelConfig, e *Device) { n.Edges.Device = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tcq *TunnelConfigQuery) loadDevice(ctx context.Context, query *DeviceQuery, nodes []*TunnelConfig, init func(*TunnelConfig), assign func(*TunnelConfig, *Device)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*TunnelConfig)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.Device(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tunnelconfig.DeviceColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.tunnel_config_device
		if fk == nil {
			return fmt.Errorf(`foreign-key "tunnel_config_device" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tunnel_config_device" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (tcq *TunnelConfigQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tcq.querySpec()
	_spec.Node.Columns = tcq.ctx.Fields
	if len(tcq.ctx.Fields) > 0 {
		_spec.Unique = tcq.ctx.Unique != nil && *tcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tcq.driver, _spec)
}

func (tcq *TunnelConfigQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tunnelconfig.Table, tunnelconfig.Columns, sqlgraph.NewFieldSpec(tunnelconfig.FieldID, field.TypeInt))
	_spec.From = tcq.sql
	if unique := tcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tcq.path != nil {
		_spec.Unique = true
	}
	if fields := tcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tunnelconfig.FieldID)
		for i := range fields {
			if fields[i] != tunnelconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tcq *TunnelConfigQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tcq.driver.Dialect())
	t1 := builder.Table(tunnelconfig.Table)
	columns := tcq.ctx.Fields
	if len(columns) == 0 {
		columns = tunnelconfig.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tcq.sql != nil {
		selector = tcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tcq.ctx.Unique != nil && *tcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tcq.predicates {
		p(selector)
	}
	for _, p := range tcq.order {
		p(selector)
	}
	if offset := tcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TunnelConfigGroupBy is the group-by builder for TunnelConfig entities.
type TunnelConfigGroupBy struct {
	selector
	build *TunnelConfigQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tcgb *TunnelConfigGroupBy) Aggregate(fns ...AggregateFunc) *TunnelConfigGroupBy {
	tcgb.fns = append(tcgb.fns, fns...)
	return tcgb
}

// Scan applies the selector query and scans the result into the given value.
func (tcgb *TunnelConfigGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tcgb.build.ctx, "GroupBy")
	if err := tcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TunnelConfigQuery, *TunnelConfigGroupBy](ctx, tcgb.build, tcgb, tcgb.build.inters, v)
}

func (tcgb *TunnelConfigGroupBy) sqlScan(ctx context.Context, root *TunnelConfigQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tcgb.fns))
	for _, fn := range tcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tcgb.flds)+len(tcgb.fns))
		for _, f := range *tcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TunnelConfigSelect is the builder for selecting fields of TunnelConfig entities.
type TunnelConfigSelect struct {
	*TunnelConfigQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tcs *TunnelConfigSelect) Aggregate(fns ...AggregateFunc) *TunnelConfigSelect {
	tcs.fns = append(tcs.fns, fns...)
	return tcs
}

// Scan applies the selector query and scans the result into the given value.
func (tcs *TunnelConfigSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tcs.ctx, "Select")
	if err := tcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TunnelConfigQuery, *TunnelConfigSelect](ctx, tcs.TunnelConfigQuery, tcs, tcs.inters, v)
}

func (tcs *TunnelConfigSelect) sqlScan(ctx context.Context, root *TunnelConfigQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tcs.fns))
	for _, fn := range tcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
