// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rahnit-rmm/ent/predicate"
	"rahnit-rmm/ent/user"
	"rahnit-rmm/util"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (uu *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetUsername sets the "username" field.
func (uu *UserUpdate) SetUsername(s string) *UserUpdate {
	uu.mutation.SetUsername(s)
	return uu
}

// SetPasswordClientHashingOptions sets the "password_client_hashing_options" field.
func (uu *UserUpdate) SetPasswordClientHashingOptions(up *util.ArgonParameters) *UserUpdate {
	uu.mutation.SetPasswordClientHashingOptions(up)
	return uu
}

// SetPasswordServerHashingOptions sets the "password_server_hashing_options" field.
func (uu *UserUpdate) SetPasswordServerHashingOptions(up *util.ArgonParameters) *UserUpdate {
	uu.mutation.SetPasswordServerHashingOptions(up)
	return uu
}

// SetPasswordDoubleHashed sets the "password_double_hashed" field.
func (uu *UserUpdate) SetPasswordDoubleHashed(b []byte) *UserUpdate {
	uu.mutation.SetPasswordDoubleHashed(b)
	return uu
}

// SetCertificate sets the "certificate" field.
func (uu *UserUpdate) SetCertificate(s string) *UserUpdate {
	uu.mutation.SetCertificate(s)
	return uu
}

// SetEncryptedPrivateKey sets the "encrypted_private_key" field.
func (uu *UserUpdate) SetEncryptedPrivateKey(s string) *UserUpdate {
	uu.mutation.SetEncryptedPrivateKey(s)
	return uu
}

// SetTotpSecret sets the "totp_secret" field.
func (uu *UserUpdate) SetTotpSecret(s string) *UserUpdate {
	uu.mutation.SetTotpSecret(s)
	return uu
}

// Mutation returns the UserMutation object of the builder.
func (uu *UserUpdate) Mutation() *UserMutation {
	return uu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uu *UserUpdate) check() error {
	if v, ok := uu.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if v, ok := uu.mutation.PasswordDoubleHashed(); ok {
		if err := user.PasswordDoubleHashedValidator(v); err != nil {
			return &ValidationError{Name: "password_double_hashed", err: fmt.Errorf(`ent: validator failed for field "User.password_double_hashed": %w`, err)}
		}
	}
	if v, ok := uu.mutation.Certificate(); ok {
		if err := user.CertificateValidator(v); err != nil {
			return &ValidationError{Name: "certificate", err: fmt.Errorf(`ent: validator failed for field "User.certificate": %w`, err)}
		}
	}
	if v, ok := uu.mutation.EncryptedPrivateKey(); ok {
		if err := user.EncryptedPrivateKeyValidator(v); err != nil {
			return &ValidationError{Name: "encrypted_private_key", err: fmt.Errorf(`ent: validator failed for field "User.encrypted_private_key": %w`, err)}
		}
	}
	return nil
}

func (uu *UserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := uu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := uu.mutation.PasswordClientHashingOptions(); ok {
		_spec.SetField(user.FieldPasswordClientHashingOptions, field.TypeJSON, value)
	}
	if value, ok := uu.mutation.PasswordServerHashingOptions(); ok {
		_spec.SetField(user.FieldPasswordServerHashingOptions, field.TypeJSON, value)
	}
	if value, ok := uu.mutation.PasswordDoubleHashed(); ok {
		_spec.SetField(user.FieldPasswordDoubleHashed, field.TypeBytes, value)
	}
	if value, ok := uu.mutation.Certificate(); ok {
		_spec.SetField(user.FieldCertificate, field.TypeString, value)
	}
	if value, ok := uu.mutation.EncryptedPrivateKey(); ok {
		_spec.SetField(user.FieldEncryptedPrivateKey, field.TypeString, value)
	}
	if value, ok := uu.mutation.TotpSecret(); ok {
		_spec.SetField(user.FieldTotpSecret, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUsername sets the "username" field.
func (uuo *UserUpdateOne) SetUsername(s string) *UserUpdateOne {
	uuo.mutation.SetUsername(s)
	return uuo
}

// SetPasswordClientHashingOptions sets the "password_client_hashing_options" field.
func (uuo *UserUpdateOne) SetPasswordClientHashingOptions(up *util.ArgonParameters) *UserUpdateOne {
	uuo.mutation.SetPasswordClientHashingOptions(up)
	return uuo
}

// SetPasswordServerHashingOptions sets the "password_server_hashing_options" field.
func (uuo *UserUpdateOne) SetPasswordServerHashingOptions(up *util.ArgonParameters) *UserUpdateOne {
	uuo.mutation.SetPasswordServerHashingOptions(up)
	return uuo
}

// SetPasswordDoubleHashed sets the "password_double_hashed" field.
func (uuo *UserUpdateOne) SetPasswordDoubleHashed(b []byte) *UserUpdateOne {
	uuo.mutation.SetPasswordDoubleHashed(b)
	return uuo
}

// SetCertificate sets the "certificate" field.
func (uuo *UserUpdateOne) SetCertificate(s string) *UserUpdateOne {
	uuo.mutation.SetCertificate(s)
	return uuo
}

// SetEncryptedPrivateKey sets the "encrypted_private_key" field.
func (uuo *UserUpdateOne) SetEncryptedPrivateKey(s string) *UserUpdateOne {
	uuo.mutation.SetEncryptedPrivateKey(s)
	return uuo
}

// SetTotpSecret sets the "totp_secret" field.
func (uuo *UserUpdateOne) SetTotpSecret(s string) *UserUpdateOne {
	uuo.mutation.SetTotpSecret(s)
	return uuo
}

// Mutation returns the UserMutation object of the builder.
func (uuo *UserUpdateOne) Mutation() *UserMutation {
	return uuo.mutation
}

// Where appends a list predicates to the UserUpdate builder.
func (uuo *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated User entity.
func (uuo *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uuo *UserUpdateOne) check() error {
	if v, ok := uuo.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if v, ok := uuo.mutation.PasswordDoubleHashed(); ok {
		if err := user.PasswordDoubleHashedValidator(v); err != nil {
			return &ValidationError{Name: "password_double_hashed", err: fmt.Errorf(`ent: validator failed for field "User.password_double_hashed": %w`, err)}
		}
	}
	if v, ok := uuo.mutation.Certificate(); ok {
		if err := user.CertificateValidator(v); err != nil {
			return &ValidationError{Name: "certificate", err: fmt.Errorf(`ent: validator failed for field "User.certificate": %w`, err)}
		}
	}
	if v, ok := uuo.mutation.EncryptedPrivateKey(); ok {
		if err := user.EncryptedPrivateKeyValidator(v); err != nil {
			return &ValidationError{Name: "encrypted_private_key", err: fmt.Errorf(`ent: validator failed for field "User.encrypted_private_key": %w`, err)}
		}
	}
	return nil
}

func (uuo *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := uuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := uuo.mutation.PasswordClientHashingOptions(); ok {
		_spec.SetField(user.FieldPasswordClientHashingOptions, field.TypeJSON, value)
	}
	if value, ok := uuo.mutation.PasswordServerHashingOptions(); ok {
		_spec.SetField(user.FieldPasswordServerHashingOptions, field.TypeJSON, value)
	}
	if value, ok := uuo.mutation.PasswordDoubleHashed(); ok {
		_spec.SetField(user.FieldPasswordDoubleHashed, field.TypeBytes, value)
	}
	if value, ok := uuo.mutation.Certificate(); ok {
		_spec.SetField(user.FieldCertificate, field.TypeString, value)
	}
	if value, ok := uuo.mutation.EncryptedPrivateKey(); ok {
		_spec.SetField(user.FieldEncryptedPrivateKey, field.TypeString, value)
	}
	if value, ok := uuo.mutation.TotpSecret(); ok {
		_spec.SetField(user.FieldTotpSecret, field.TypeString, value)
	}
	_node = &User{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
