// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Device is the predicate function for device builders.
type Device func(*sql.Selector)

// Revocation is the predicate function for revocation builders.
type Revocation func(*sql.Selector)

// TunnelConfig is the predicate function for tunnelconfig builders.
type TunnelConfig func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
